import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service — Apply Pilot',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors duration-200 mb-8 cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to home
        </Link>

        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: May 14, 2025</p>

        <div className="glass-strong rounded-2xl p-8 shadow-sm space-y-8 text-sm text-foreground leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Apply Pilot (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">2. Description of Service</h2>
            <p>
              Apply Pilot is a job application tracking platform that provides tools for managing job applications, AI-powered resume analysis, and cover letter generation. The Service is provided &quot;as is&quot; and may be updated, modified, or discontinued at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">3. User Accounts</h2>
            <p className="mb-2">When you create an account, you agree to:</p>
            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
              <li>Provide accurate and complete information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized access</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">4. Acceptable Use</h2>
            <p className="mb-2">You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Upload malicious content or attempt to exploit vulnerabilities</li>
              <li>Use automated tools to scrape or extract data from the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">5. Intellectual Property</h2>
            <p>
              The Service, including its design, code, and branding, is owned by Apply Pilot. Content you create (applications, resumes, cover letters) remains yours. By using the Service, you grant us a limited license to process your content solely to provide the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">6. AI-Generated Content</h2>
            <p>
              Resume analyses and cover letters generated by our AI tools are provided as suggestions only. You are responsible for reviewing, editing, and verifying all AI-generated content before use. We do not guarantee the accuracy, completeness, or suitability of AI outputs.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">7. Limitation of Liability</h2>
            <p>
              Apply Pilot is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to lost data, missed opportunities, or reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">8. Termination</h2>
            <p>
              We may suspend or terminate your account at any time for violation of these terms. You may delete your account at any time. Upon termination, your data will be deleted in accordance with our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">9. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the new terms. We will notify users of significant changes via email or in-app notification.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">10. Contact</h2>
            <p>
              If you have questions about these Terms of Service, please contact us at{' '}
              <a href="mailto:support@applypilot.com" className="text-primary hover:text-primary/80 transition-colors duration-200">
                support@applypilot.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
